version: '3.8'
services:
  portal:
    build: .
    image: portal_sso:latest
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
    restart: always
    networks:
      - portal-net

networks:
  portal-net:
    driver: bridge
