-- Migración para crear tablas del módulo RRHH (Versión Completa)

-- 1. Tablas de Atributos del Empleado (Dimensiones)
CREATE TABLE IF NOT EXISTS public.rrhh_marital_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.rrhh_contract_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.rrhh_pension_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.rrhh_health_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.rrhh_departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    parent_id BIGINT REFERENCES public.rrhh_departments(id),
    manager_id UUID, -- Referencia a auth.users o a employees
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.rrhh_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    department_id BIGINT REFERENCES public.rrhh_departments(id),
    base_salary NUMERIC(12, 2) DEFAULT 0,
    description TEXT,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.rrhh_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    break_minutes INTEGER DEFAULT 60,
    work_days INTEGER[] DEFAULT '{1,2,3,4,5}', -- 1=Lunes, 7=Domingo (ISO)
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 2. Tabla Principal de Empleados
CREATE TABLE IF NOT EXISTS public.employees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rut TEXT NOT NULL UNIQUE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone TEXT,
    birth_date DATE,
    address TEXT,
    city TEXT,
    region TEXT,
    
    -- Relaciones
    marital_status_id BIGINT REFERENCES public.rrhh_marital_status(id),
    nationality TEXT DEFAULT 'Chilena',
    
    -- Contrato
    contract_type_id BIGINT REFERENCES public.rrhh_contract_types(id),
    job_id BIGINT REFERENCES public.rrhh_jobs(id),
    department_id BIGINT REFERENCES public.rrhh_departments(id),
    shift_id BIGINT REFERENCES public.rrhh_shifts(id),
    manager_id UUID REFERENCES public.employees(id),
    
    hire_date DATE NOT NULL,
    termination_date DATE,
    active BOOLEAN DEFAULT TRUE,
    
    -- Previsional
    pension_provider_id BIGINT REFERENCES public.rrhh_pension_providers(id),
    health_provider_id BIGINT REFERENCES public.rrhh_health_providers(id),
    
    -- Datos Bancarios
    bank_name TEXT,
    account_type TEXT,
    account_number TEXT,
    
    user_id UUID REFERENCES auth.users(id), -- Link opcional a auth.users
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 3. Historial de Asistencia
CREATE TABLE IF NOT EXISTS public.rrhh_attendance (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id UUID NOT NULL REFERENCES public.employees(id),
    check_in TIMESTAMP WITH TIME ZONE NOT NULL,
    check_out TIMESTAMP WITH TIME ZONE,
    date DATE GENERATED ALWAYS AS (check_in::DATE) STORED,
    status TEXT DEFAULT 'present', -- present, late, absent, etc.
    source TEXT DEFAULT 'web', -- web, biometric, app
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 4. Ausencias y Licencias
CREATE TABLE IF NOT EXISTS public.rrhh_absences (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id UUID NOT NULL REFERENCES public.employees(id),
    type TEXT NOT NULL, -- vacation, sick_leave, administrative, other
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason TEXT,
    status TEXT DEFAULT 'pending', -- pending, approved, rejected
    approved_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 5. Nómina (Cabecera y Detalle simple)
CREATE TABLE IF NOT EXISTS public.rrhh_payrolls (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id UUID NOT NULL REFERENCES public.employees(id),
    period_date DATE NOT NULL, -- Primer día del mes pagado
    
    base_salary NUMERIC(12, 0) NOT NULL,
    taxable_income NUMERIC(12, 0) NOT NULL,
    total_discounts NUMERIC(12, 0) NOT NULL,
    net_salary NUMERIC(12, 0) NOT NULL,
    status TEXT DEFAULT 'draft', -- draft, processed, paid
    
    details JSONB, -- Detalles completos calculados en JSON
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.rrhh_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rrhh_departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;

-- Políticas permisivas por defecto para autenticados (Ajustar según necesidad real)
CREATE POLICY "Permitir lectura a autenticados" ON public.rrhh_jobs FOR SELECT TO authenticated USING (true);
CREATE POLICY "Permitir todo a autenticados" ON public.rrhh_jobs FOR ALL TO authenticated USING (true);

CREATE POLICY "Permitir lectura a autenticados" ON public.rrhh_departments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Permitir todo a autenticados" ON public.rrhh_departments FOR ALL TO authenticated USING (true);

CREATE POLICY "Permitir lectura a autenticados" ON public.employees FOR SELECT TO authenticated USING (true);
CREATE POLICY "Permitir todo a autenticados" ON public.employees FOR ALL TO authenticated USING (true);
